/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_test_opus_OpusEncoder */

#ifndef _Included_cn_com_test_opus_OpusEncoder
#define _Included_cn_com_test_opus_OpusEncoder
#ifdef __cplusplus
extern "C" {
#endif
#undef cn_com_test_opus_OpusEncoder_OPUS_APPLICATION_VOIP
#define cn_com_test_opus_OpusEncoder_OPUS_APPLICATION_VOIP 2048L
#undef cn_com_test_opus_OpusEncoder_OPUS_APPLICATION_AUDIO
#define cn_com_test_opus_OpusEncoder_OPUS_APPLICATION_AUDIO 2049L
#undef cn_com_test_opus_OpusEncoder_OPUS_APPLICATION_RESTRICTED_LOWDELAY
#define cn_com_test_opus_OpusEncoder_OPUS_APPLICATION_RESTRICTED_LOWDELAY 2051L
/*
 * Class:     cn_com_test_opus_OpusEncoder
 * Method:    nativeInitEncoder
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_com_test_opus_OpusEncoder_nativeInitEncoder
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cn_com_test_opus_OpusEncoder
 * Method:    nativeEncodeShorts
 * Signature: ([SI[B)I
 */
JNIEXPORT jint JNICALL Java_cn_com_test_opus_OpusEncoder_nativeEncodeShorts___3SI_3B
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray);

/*
 * Class:     cn_com_test_opus_OpusEncoder
 * Method:    nativeEncodeBytes
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_cn_com_test_opus_OpusEncoder_nativeEncodeBytes___3BI_3B
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

/*
 * Class:     cn_com_test_opus_OpusEncoder
 * Method:    nativeEncodeShorts
 * Signature: ([SI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_com_test_opus_OpusEncoder_nativeEncodeShorts___3SI
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     cn_com_test_opus_OpusEncoder
 * Method:    nativeEncodeBytes
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_com_test_opus_OpusEncoder_nativeEncodeBytes___3BI
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     cn_com_test_opus_OpusEncoder
 * Method:    nativeReleaseEncoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_com_test_opus_OpusEncoder_nativeReleaseEncoder
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
