/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_test_opus_OpusDecoder */

#ifndef _Included_cn_com_test_opus_OpusDecoder
#define _Included_cn_com_test_opus_OpusDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_test_opus_OpusDecoder
 * Method:    nativeInitDecoder
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_com_test_opus_OpusDecoder_nativeInitDecoder
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_com_test_opus_OpusDecoder
 * Method:    nativeDecodeShorts
 * Signature: ([B[S)I
 */
JNIEXPORT jint JNICALL Java_cn_com_test_opus_OpusDecoder_nativeDecodeShorts___3B_3S
  (JNIEnv *, jobject, jbyteArray, jshortArray);

/*
 * Class:     cn_com_test_opus_OpusDecoder
 * Method:    nativeDecodeShorts
 * Signature: ([B)[S
 */
JNIEXPORT jshortArray JNICALL Java_cn_com_test_opus_OpusDecoder_nativeDecodeShorts___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cn_com_test_opus_OpusDecoder
 * Method:    nativeDecodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_com_test_opus_OpusDecoder_nativeDecodeFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_com_test_opus_OpusDecoder
 * Method:    nativeReleaseDecoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_com_test_opus_OpusDecoder_nativeReleaseDecoder
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
